name: Release

on:
  pull_request:
    types:
    - closed
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
    release:
        name: Release
        if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
        permissions:
          contents: write
        uses: Alfresco/alfresco-build-tools/.github/workflows/reusable-release.yml@v18.15.0
        with:
          release_type_override: ${{ inputs.release_type }}
        secrets:
          BOT_GITHUB_TOKEN: ${{ secrets.github_token }}
